#+title: Defining the Christmas Spirit

*The /Christmas Spirit/ is the condition of abiding in the numinous
experience of kairotic participation in Christ's advent.*

What does this mean?

Christ's advent can be viewed chronologically and kairotically.
Chronologically, advent is a historical past reality. Kairotically,
Christ's arrival is an eternal moment that we make a special effort to
abide in at the end of every year.

We participate in advent chronologically through memorializing
activities which bring to mind the historical advent account. Such
activities include: reading the Christmas story, performing Christmas
pageants, and setting up nativity sets. These are important traditions
that help us to keep the facts straight. However, they tend to produce a
comparatively impersonal, observationa, or external persective. It is
difficult to abide in and be filled with a historical fact. Rather, the
past occurence makes possible the existence of a present condition...

While Christ's advent occurred historically, it is also an eternal
kairotic moment. If we desire to enter into the reality of this eternal
moment, we must be filled with the joy of His presence. This joy cannot
be repressed. It overflows as the characteristic Christmas virtues:
generosity and charity. These virtues are a divine blessing and the
natural consequence of Christ's presence. In Scripture, they are
referred to as "peace on earth, good will towards men".
