#+title: Roger Farrell's notes

Welcome to my personal notes. I am loosely following the [[https://zettelkasten.de/overview/][zettelkasten]]
method to create a hyperlinked network of information, similar to a
wiki. This is not a blog. It is intended firstly for my own
reference. Notwithstanding, you are more than welcome to explore to
your heart's content.

As per zettelkasten methodology, these notes are not organized in a
hierarchy. Topics/categories are fluid, overlapping and interrelating
as they grow organically. Instead of folders or some other
hierarchical organization, the below registry (list of topics) serves
as my entry point. For more information see
[[file:my-personal-zettelkasten-workflow.org]].

To see a frequently-updated history of stuff I am currently learning
about, check out my learning log: [[file:references/learning-log.org]].

* The registry
:PROPERTIES:
:CUSTOM_ID: the-registry
:END:
- [[file:art.org]]
- [[file:computer.org]]
- [[file:development.org]]
- [[file:diy.org]]
- [[file:education.org]]
- [[file:history.org]]
- [[file:mythology.org]]
- [[file:religion.org]]
- [[file:symbolism.org]]
- [[file:zettelkasten.org]]
