#+title: My personal zettelkasten workflow

* Real time idea capture
:PROPERTIES:
:CUSTOM_ID: real-time-idea-capture
:END:
I find that I am rarely ready to take a note when the idea first
strikes. The first encounter is messy. It takes time and some digestion
for the idea to take shape and start to show how it is connected to
other related ideas. During this period, I try to make an entry in
[[file:references/learning-log.org]]. Logging the thought prevents it from
being lost forever. Once an idea has become sufficiently mature to write
about, I write an initial note in my inbox folder. The note will stay
here until two conditions are met:

- The idea has been clearly represented in a way that is compliant with
  my note taking conventions and is accessible to my future self.
- I have linked to the note from at least one pre-existing note.

* Navigating my notes
:PROPERTIES:
:CUSTOM_ID: navigating-my-notes
:END:
The zettelkasten method yields a web of hyperlinked notes. A strategy
for creating entry points into this web is essential to efficient
navigation as memory fades. Many people employ the folgezettel
schema[fn:1] for this purpose. However, I have chosen to do this via
structure (or hub) notes.

Structure notes are constituted of hierarchical lists of other notes
mapped by a given topic. I will be using tags to implement this feature
as can be found in my [[file:taking-notes-in-vim.org][note-taking
workflow]]. At the time of creation, every note will be linked to at
least one structure note. Structure notes must be linked to at least one
other structure note or my registry: [[file:index.org]].

[fn:1] The folgezettel schema is an efficient way to define hierarchical
       IDs for notes in
       real-time:[[file:references/the-great-folgezettel-debate.org]]
