#+title: Why CLIs are better for humans

It seems natural to perceive command line interfaces as primitive,
old-fashioned, and more computer-friendly than human-friendly. Yet, it
is also not uncommon to develop a preference for CLIs after sufficient
exposure. I think the reason for this is simple.

CLIs are actually very human friendly, they simply presume a higher
degree of contextual awareness. In other words, CLIs abstract away fewer
details than graphical interfaces. While this makes the initial learning
curve steeper, the payoff is very significant. Because CLIs force you to
interact with the underlying concepts behind a tool, they are great
learning environments. This learning organically develops into the
perfect foundation for automated workflows via shell scripts, etc..

By way of example, one could use Vim and sips to quickly convert the
color profile for a batch of images.[fn:1] This is one step away from
writing a shell script.

[fn:1] See [[file:references/batching-shell-commands-with-vim.org]] and
       [[file:references/change-image-color-profile-with-sips.org]].
