#+title: Guide: Markdown-to-InDesign workflow

#+author: Roger Farrell
I prefer to spend as little time in InDesign as possible. My preferred
typsetting tools are markdown and [[https://pandoc.org][Pandoc]]. This
is a description of how I use Pandoc's markdown syntax to generate
pre-styled manuscripts that cleanly import into InDesign.

Pandoc is just a great tool. It can do almost anything with text-based
files. For this workflow, we only need to learn a couple of its perks.

** Fenced divs and spans
:PROPERTIES:
:CUSTOM_ID: fenced-divs-and-spans
:END:
Pandoc supports fenced divs with the following syntax.[fn:1]

#+begin_src markdown
``` {some attributes}
I am inside a div.
```
#+end_src

Similarly, spans are supported like this:

#+begin_src markdown
[I am a span.]{some attributes}
#+end_src

** Custom styles
:PROPERTIES:
:CUSTOM_ID: custom-styles
:END:
Custom styles can be set as attributes for fenced divs and spans.[fn:2]

#+begin_src markdown
``` {custom-style="myParagraphStyle"}
I am a paragraph. I have a special [character style.]{custom-style="myCharacterStyle"}
```
#+end_src

** Pandoc supports ICML
:PROPERTIES:
:CUSTOM_ID: pandoc-supports-icml
:END:
Conveniently, Pandoc supports conversion to ICML (InCopy's native file
type).[fn:3] Custom styles set using the above method are converted
directly to paragraph and character styles. The best part is that the
styles are automatically created to reflect the semantic hierarchy of
the Manuscript. If you are familiar with HTML, you will notice they
resemble well-organized CSS selectors.

#+begin_src zsh
pandoc manuscript.md --standalone --output=manuscript.icml
#+end_src

/Note: The =--standalone= flag is required for correct output./

** Importing into InDesign
:PROPERTIES:
:CUSTOM_ID: importing-into-indesign
:END:
At this point, you can import the ICML directly into an InDesign story
with the /place/ command. In theory, you could make changes solely in
the markdown, rebuild the ICML, and never touch your content in
InDesign.

[fn:1] [[https://pandoc.org/MANUAL.html#extension-fenced_divs]]

[fn:2] [[https://pandoc.org/MANUAL.html#custom-styles]]

[fn:3] [[https://pandoc.org/MANUAL.html#custom-styles]]
